version: '3'
services:
  factorio:
    build: .
    ports:
      - "34197:34197/udp"
      - "27015:27015/udp"
    command: "/opt/factorio/bin/x64/factorio --start-server /opt/factorio/saves/_autosave2.zip"
